# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'Task_Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'lottie-ios'
  pod 'SVProgressHUD'

  # Pods for Task_Manager

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
