# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Task_Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'lottie-ios'

  # Pods for Task_Manager

end
